defmodule BeamSlackWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :beamslack

  # Sessions exist only so LiveDashboard has one. The API itself authenticates
  # with a bearer token and is stateless.
  @session_options [
    store: :cookie,
    key: "_beamslack_key",
    signing_salt: "8mMJ0Iqf",
    same_site: "Lax"
  ]

  # The WebSocket entry point. One socket connection per browser tab, carrying
  # any number of channels. Authentication happens once, in UserSocket.connect/3.
  socket "/socket", BeamSlackWeb.UserSocket,
    websocket: [connect_info: [:peer_data, :user_agent]],
    longpoll: false

  # LiveDashboard is the only LiveView in this otherwise API-only app, so its
  # socket and the session it needs exist in dev only.
  if Application.compile_env(:beamslack, :dev_routes) do
    socket "/live", Phoenix.LiveView.Socket,
      websocket: [connect_info: [session: @session_options]]
  end

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :beamslack,
    gzip: not code_reloading?,
    only: BeamSlackWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :beamslack
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head

  if Application.compile_env(:beamslack, :dev_routes) do
    plug Plug.Session, @session_options
  end

  plug BeamSlackWeb.Router
end
