import Config

# Configure your database
config :beamslack, BeamSlack.Repo,
  username: System.get_env("POSTGRES_USER", "postgres"),
  password: System.get_env("POSTGRES_PASSWORD", "postgres"),
  hostname: System.get_env("POSTGRES_HOST", "localhost"),
  port: String.to_integer(System.get_env("POSTGRES_PORT", "5432")),
  database: System.get_env("POSTGRES_DB", "beamslack_dev"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# LiveDashboard at /dev/dashboard and the fault-injection endpoints at
# /dev/faults. Both are compiled out of every other environment.
config :beamslack, dev_routes: true

config :beamslack, BeamSlackWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "dRfQufJZb/0zwhdBUgs3vmf4Dc+znjl5w8c9k2rJM5G94BccnJmh/sNUcfdG83+Z",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Development logs keep the metadata. Reading `channel_id=... duration_ms=...`
# next to the message is the whole point of the structured fields, and Track 3
# spends a lot of time reading logs.
config :logger, :default_formatter, format: "[$level] $message $metadata\n"

# Supervisor reports -- "child X started", "child X terminated", "reached
# max_restarts" -- are emitted by OTP under the :sasl domain, and Elixir's Logger
# filters that domain out by default. Which means the default configuration hides
# exactly the events a supervision tree exists to produce, and you can watch a
# tree collapse with nothing in the log but the first crash.
#
# Turning this on is the single most useful thing in Track 3. Try
# `mix beamslack.kill presence` with and without it.
config :logger,
  handle_sasl_reports: true,
  handle_otp_reports: true

# ...but not the "child started" half of them, which is a few hundred lines every
# boot and tells you nothing you did not already expect. `:logger_filters.progress/2`
# with `:stop` drops progress reports and keeps the crash and terminate reports,
# which are the ones worth reading. Delete this to see a supervision tree being
# built, once.
config :logger, :default_handler, filters: [progress: {&:logger_filters.progress/2, :stop}]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
